app:
    static_folder: /static
    secret_key: secret!
    debug: true
    host: "0.0.0.0"
    namespace: /playermap
    port: 5000
    timer: 60
    game_version: 0.5.3
    logger: true
    engineio_logger: true

database:
    host: sql
    user: root
    pass: pwd
    port: 3303
    charset: utf8mb4
    database: None

frontend:
    admin: true
    title: Online playermap
    map_id: 0
    ignored: 0

0.5.3:
    name: 0.5.3
    mapfile: /static/img/map/azeroth-0.5.3.jpg
    logofile: /static/img/wowlogo.png

viewport:
    offset: 750

maps_static_data: 
    # Eastern Kingdoms, 0.5.3
    0:
        mapLeftPoint: 4267.765836313618
        mapTopPoint: 4657.975130879346
        mapWidth: 10568.022008253096
        mapHeight: 19980.94603271984
        imageWidth: 345
        imageHeight: 650
        # 2000, 3770
    # Kalimdor 0.5.3:
    1:
        mapLeftPoint:  5042.486592588943
        mapTopPoint: 11763.32433764838
        mapWidth: 13100.059130777572 
        mapHeight: 24611.604572321823 
        imageWidth: 345
        imageHeight: 650
