version: '3.9'

services:
  playermap:
    image: ${PROJECT}:${OS_TAG}
    build: {context: ., dockerfile: app/etc/containers/playermap-flask/Dockerfile}
    hostname: ${PROJECT}
    container_name: ${PROJECT}
    tty: true
    volumes:
      - ./app:/opt/playermap-flask
    ports:
      - 5000:5000
    restart: on-failure

  sql:
    image: ${PROJECT}-db:${DB_TAG}
    build: app/etc/containers/db
    container_name: ${PROJECT}-db
    hostname: ${PROJECT}-db
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
    ports:
      - "3306:3306"
    volumes:
      - ./app/etc/databases/:/etc/databases/
    restart: on-failure
    profiles:
      - sql
    
networks:
  default:
    name: alpha-core-network
    external: true
